/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PlanejamentoRouteImport } from './routes/planejamento'
import { Route as PagamentoConfirmadoMensalRouteImport } from './routes/pagamento-confirmado-mensal'
import { Route as PagamentoConfirmadoAnualRouteImport } from './routes/pagamento-confirmado-anual'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as InclusaoRouteImport } from './routes/inclusao'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PlanejamentoEiRouteImport } from './routes/planejamento.ei'
import { Route as PlanejamentoAtividadeRouteImport } from './routes/planejamento.atividade'
import { Route as InclusaoPeiRouteImport } from './routes/inclusao.pei'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as ApiSofiaSuggestionsRouteImport } from './routes/api/sofia.suggestions'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanejamentoRoute = PlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoConfirmadoMensalRoute =
  PagamentoConfirmadoMensalRouteImport.update({
    id: '/pagamento-confirmado-mensal',
    path: '/pagamento-confirmado-mensal',
    getParentRoute: () => rootRouteImport,
  } as any)
const PagamentoConfirmadoAnualRoute =
  PagamentoConfirmadoAnualRouteImport.update({
    id: '/pagamento-confirmado-anual',
    path: '/pagamento-confirmado-anual',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InclusaoRoute = InclusaoRouteImport.update({
  id: '/inclusao',
  path: '/inclusao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PlanejamentoEiRoute = PlanejamentoEiRouteImport.update({
  id: '/ei',
  path: '/ei',
  getParentRoute: () => PlanejamentoRoute,
} as any)
const PlanejamentoAtividadeRoute = PlanejamentoAtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => PlanejamentoRoute,
} as any)
const InclusaoPeiRoute = InclusaoPeiRouteImport.update({
  id: '/pei',
  path: '/pei',
  getParentRoute: () => InclusaoRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSofiaSuggestionsRoute = ApiSofiaSuggestionsRouteImport.update({
  id: '/api/sofia/suggestions',
  path: '/api/sofia/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/inclusao': typeof InclusaoRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pagamento-confirmado-anual': typeof PagamentoConfirmadoAnualRoute
  '/pagamento-confirmado-mensal': typeof PagamentoConfirmadoMensalRoute
  '/planejamento': typeof PlanejamentoRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/inclusao/pei': typeof InclusaoPeiRoute
  '/planejamento/atividade': typeof PlanejamentoAtividadeRoute
  '/planejamento/ei': typeof PlanejamentoEiRoute
  '/admin/': typeof AdminIndexRoute
  '/api/sofia/suggestions': typeof ApiSofiaSuggestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/inclusao': typeof InclusaoRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pagamento-confirmado-anual': typeof PagamentoConfirmadoAnualRoute
  '/pagamento-confirmado-mensal': typeof PagamentoConfirmadoMensalRoute
  '/planejamento': typeof PlanejamentoRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/inclusao/pei': typeof InclusaoPeiRoute
  '/planejamento/atividade': typeof PlanejamentoAtividadeRoute
  '/planejamento/ei': typeof PlanejamentoEiRoute
  '/admin': typeof AdminIndexRoute
  '/api/sofia/suggestions': typeof ApiSofiaSuggestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/assistente': typeof AssistenteRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/inclusao': typeof InclusaoRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pagamento-confirmado-anual': typeof PagamentoConfirmadoAnualRoute
  '/pagamento-confirmado-mensal': typeof PagamentoConfirmadoMensalRoute
  '/planejamento': typeof PlanejamentoRouteWithChildren
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/inclusao/pei': typeof InclusaoPeiRoute
  '/planejamento/atividade': typeof PlanejamentoAtividadeRoute
  '/planejamento/ei': typeof PlanejamentoEiRoute
  '/admin/': typeof AdminIndexRoute
  '/api/sofia/suggestions': typeof ApiSofiaSuggestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/assistente'
    | '/auth'
    | '/configuracoes'
    | '/inclusao'
    | '/onboarding'
    | '/pagamento-confirmado-anual'
    | '/pagamento-confirmado-mensal'
    | '/planejamento'
    | '/relatorios'
    | '/reset-password'
    | '/admin/usuarios'
    | '/inclusao/pei'
    | '/planejamento/atividade'
    | '/planejamento/ei'
    | '/admin/'
    | '/api/sofia/suggestions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/assistente'
    | '/auth'
    | '/configuracoes'
    | '/inclusao'
    | '/onboarding'
    | '/pagamento-confirmado-anual'
    | '/pagamento-confirmado-mensal'
    | '/planejamento'
    | '/relatorios'
    | '/reset-password'
    | '/admin/usuarios'
    | '/inclusao/pei'
    | '/planejamento/atividade'
    | '/planejamento/ei'
    | '/admin'
    | '/api/sofia/suggestions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/assistente'
    | '/auth'
    | '/configuracoes'
    | '/inclusao'
    | '/onboarding'
    | '/pagamento-confirmado-anual'
    | '/pagamento-confirmado-mensal'
    | '/planejamento'
    | '/relatorios'
    | '/reset-password'
    | '/admin/usuarios'
    | '/inclusao/pei'
    | '/planejamento/atividade'
    | '/planejamento/ei'
    | '/admin/'
    | '/api/sofia/suggestions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  AssistenteRoute: typeof AssistenteRoute
  AuthRoute: typeof AuthRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  InclusaoRoute: typeof InclusaoRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PagamentoConfirmadoAnualRoute: typeof PagamentoConfirmadoAnualRoute
  PagamentoConfirmadoMensalRoute: typeof PagamentoConfirmadoMensalRoute
  PlanejamentoRoute: typeof PlanejamentoRouteWithChildren
  RelatoriosRoute: typeof RelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiSofiaSuggestionsRoute: typeof ApiSofiaSuggestionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planejamento': {
      id: '/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof PlanejamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-confirmado-mensal': {
      id: '/pagamento-confirmado-mensal'
      path: '/pagamento-confirmado-mensal'
      fullPath: '/pagamento-confirmado-mensal'
      preLoaderRoute: typeof PagamentoConfirmadoMensalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-confirmado-anual': {
      id: '/pagamento-confirmado-anual'
      path: '/pagamento-confirmado-anual'
      fullPath: '/pagamento-confirmado-anual'
      preLoaderRoute: typeof PagamentoConfirmadoAnualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inclusao': {
      id: '/inclusao'
      path: '/inclusao'
      fullPath: '/inclusao'
      preLoaderRoute: typeof InclusaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/planejamento/ei': {
      id: '/planejamento/ei'
      path: '/ei'
      fullPath: '/planejamento/ei'
      preLoaderRoute: typeof PlanejamentoEiRouteImport
      parentRoute: typeof PlanejamentoRoute
    }
    '/planejamento/atividade': {
      id: '/planejamento/atividade'
      path: '/atividade'
      fullPath: '/planejamento/atividade'
      preLoaderRoute: typeof PlanejamentoAtividadeRouteImport
      parentRoute: typeof PlanejamentoRoute
    }
    '/inclusao/pei': {
      id: '/inclusao/pei'
      path: '/pei'
      fullPath: '/inclusao/pei'
      preLoaderRoute: typeof InclusaoPeiRouteImport
      parentRoute: typeof InclusaoRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/sofia/suggestions': {
      id: '/api/sofia/suggestions'
      path: '/api/sofia/suggestions'
      fullPath: '/api/sofia/suggestions'
      preLoaderRoute: typeof ApiSofiaSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InclusaoRouteChildren {
  InclusaoPeiRoute: typeof InclusaoPeiRoute
}

const InclusaoRouteChildren: InclusaoRouteChildren = {
  InclusaoPeiRoute: InclusaoPeiRoute,
}

const InclusaoRouteWithChildren = InclusaoRoute._addFileChildren(
  InclusaoRouteChildren,
)

interface PlanejamentoRouteChildren {
  PlanejamentoAtividadeRoute: typeof PlanejamentoAtividadeRoute
  PlanejamentoEiRoute: typeof PlanejamentoEiRoute
}

const PlanejamentoRouteChildren: PlanejamentoRouteChildren = {
  PlanejamentoAtividadeRoute: PlanejamentoAtividadeRoute,
  PlanejamentoEiRoute: PlanejamentoEiRoute,
}

const PlanejamentoRouteWithChildren = PlanejamentoRoute._addFileChildren(
  PlanejamentoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgendaRoute: AgendaRoute,
  AssistenteRoute: AssistenteRoute,
  AuthRoute: AuthRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  InclusaoRoute: InclusaoRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PagamentoConfirmadoAnualRoute: PagamentoConfirmadoAnualRoute,
  PagamentoConfirmadoMensalRoute: PagamentoConfirmadoMensalRoute,
  PlanejamentoRoute: PlanejamentoRouteWithChildren,
  RelatoriosRoute: RelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiSofiaSuggestionsRoute: ApiSofiaSuggestionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
